#!/bin/bash
case "$1" in
	"make")
	cd library
	make
	;;
	"run")
	cd BUILD
	./main
	;;
	"make-and-run")
	cd library
	make
	cd ../BUILD
	./main
	;;
	"clean")
	cd BUILD
	rm -f *
	;;
	*)
	echo Invalid parameter for build
	echo valid parameters: make run make-and-run clean
	;;
esac
